/**
 * Application Constants
 */

export const COLLECTIONS = {
  CUSTOMERS: 'customers',
  PRODUCTS: 'products',
  CATEGORIES: 'categories',
  BILLINGS: 'billings',
  SETTINGS: 'settings',
  COUNTERS: 'counters',
  ASSETS: 'assets',
  THEMES: 'themes',
} as const

export const SETTINGS_DOC_ID = 'global_store_settings'
export const THEME_DOC_ID = 'active_theme'

export const COUNTER_DOC_IDS = {
  PRODUCT: 'product',
  CATEGORY: 'category',
  customerYear: (year: number) => `customer_${year}`,
  billingYear: (year: number) => `billing_${year}`,
} as const

export const DEFAULT_PAGE_SIZE = 50

export const DEFAULT_TAX_RATE_PERCENT = 5

export const INITIAL_CATEGORY_NAMES = [
  'Compact',
  'Foundation',
  'Eye Shadow',
  'Eyeliner',
  'Mascara',
  'Blush',
  'Primer',
  'Base',
  'Pan Cake',
  'Concealer',
  'Nail Polish',
  'Nail Polish Remover',
  'Lip Gloss',
  'Blush On',
  'Lip Liner Pencil',
  'Glitter',
  'Makeup Kit',
  'Deo',
  'Perfumes',
  'Hair Dryer',
  'Hair Straightener',
  'Vaporiser',
  'Wax Heater',
  'Curler',
  'Face Massager',
  'Eyebrow Pencil',
  'Extra',
  'Stillman',
  'Kelly',
  'Archery',
  'Tissue',
  'Hair Spray',
  'Room Freshener',
  'Powder',
  'Mehndi Cone',
  'Slipper',
  'Wallet',
  'Sunglasses',
  'Belt',
  'Necklace',
  'Pendant',
  'Nose Pin',
  'Earrings',
  'Bindi',
  'Center Clip',
  'Claw',
  'Rubber Band',
  'Tik Tak',
  'Saree Pin',
  'Hijab Pin',
  'Banana Clip',
  'Stone Center',
  'Stone Claw',
  'Side Pin',
  'Safety Pin',
  'Comb',
  'Foot Scraper',
  'Hair Brush',
  'Nail Filer',
  'Pulker',
  'Black Head Pin',
  'Facial Band',
  'Makeup Brush',
  'Nail Cutter',
  'Hair Roller',
  'Ladies Purse',
  'Face Mask',
  'Hair Band',
  'Fair Cream',
  'Rose Water',
  'Face Wash',
  'Attar',
  'Bangles',
  'Remover',
  "O'Shea",
  'Velvet Bangles',
  'Lac Joda',
  'Thread Bangles',
  'Glass Bangles',
  'Lac Bangles',
  'Lac Kangan',
  'Shipping',
  'Decorative Candle Piece',
  'Bangles 2.4',
  'Bangles 2.2',
  'Bangles 2.6',
  'Bangles 2.8',
  'Box',
  'Packing',
  'Facial Kit',
  'Henna',
] as const

export const INITIAL_CATEGORIES = INITIAL_CATEGORY_NAMES.map((name, index) => ({
  categoryId: `CAT-${String(index + 1).padStart(6, '0')}`,
  categoryName: name,
  createdAt: { seconds: Math.floor(Date.now() / 1000), nanoseconds: 0 },
  updatedAt: { seconds: Math.floor(Date.now() / 1000), nanoseconds: 0 },
}))
